верстка футера
NataliiaValko/filmoteka-js pull request #18
Opened 2021-07-25 19:34 UTC by VitaliyVovk76

2021-07-25 22:35 UTC, NataliiaValko requested changes

2021-07-25 22:35 UTC, NataliiaValko commented on src/sass/layout/_footer.scss
> +  display: flex;
флекс тут лишний, этот тег не является родителем, это свойство ничего тут не делает

2021-07-25 22:35 UTC, NataliiaValko commented on src/partials/footer.html
> +      <div class="foorer-developed">
да мой Фюррер))) и ниже тоже Фюррер =)))

footer__developed-parth

2021-07-25 22:35 UTC, NataliiaValko commented on src/partials/footer.html
> +    <div class="footer-info">
footer__info

2021-07-25 22:35 UTC, NataliiaValko commented on src/partials/footer.html
> +      <div class="footer-copyright">
footer__copyright-parth. Просто footer-copyright не может быть блоком....он не самостоятельный...сама по себе фраза 2020 ваще ничего не несет без остального текста

2021-07-25 22:35 UTC, NataliiaValko commented on src/partials/footer.html
> +        <p class="footer-copyright__text">&copy; 2020</p>
footer__copyright-text

2021-07-25 22:35 UTC, NataliiaValko commented on src/partials/footer.html
> +        <p class="footer-copyright__text">All Rights Reserved</p>
footer__copyright-text

2021-07-25 22:35 UTC, NataliiaValko commented on src/partials/footer.html
> +        <p class="foorer-developed__text">Developed with</p>
footer__developed-text

сердечко думаю можно тут вставить просто материалс айконом из гугла. Библиотеку в главном штмл я подключила, в дискорде прислала название иконки. Цвет меняешь через color. Синтаксис КАК подключать можешь подсмотреть или у гугла, или в домашке № 10

2021-07-25 22:35 UTC, NataliiaValko commented on src/partials/footer.html
> +        <p class="foorer-developed__text">
footer__developed-text

2021-07-25 22:35 UTC, NataliiaValko commented on src/partials/footer.html
> +          by<span><a class="footer-copyright__link" href=""> GoIT Students</a></span>
footer__link

2021-07-25 22:35 UTC, NataliiaValko commented on src/sass/layout/_footer.scss
> +.footer {
не забудь в стилях тоже откорректировать классы

2021-07-25 22:35 UTC, closed without merging

2021-07-26 06:27 UTC, VitaliyVovk76 commented on src/sass/layout/_footer.scss
> +  display: flex;
флекс для псевдоелемента

2021-07-26 14:05 UTC, NataliiaValko commented on src/sass/layout/_footer.scss
> +  display: flex;
но....а не правильнее ли пседоэлемент абсолютно спозиционировать???